use Museum_DW;

ALTER TABLE [dbo].[A_B_L] NOCHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[A_D] NOCHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[Artist] NOCHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[Artwork] NOCHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[Borrowed_or_lent] NOCHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[Donation] NOCHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[Institution] NOCHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[Junk_Borrowing] NOCHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[Junk_Donation] NOCHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[Patron] NOCHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[Patron_date_joined] NOCHECK CONSTRAINT ALL;

DELETE FROM [dbo].[A_B_L];
DELETE FROM [dbo].[A_D];
DELETE FROM [dbo].[Artist];
DELETE FROM [dbo].[Artwork];
DELETE FROM [dbo].[Borrowed_or_lent];
DELETE FROM [dbo].[Donation];
DELETE FROM [dbo].[Institution];
DELETE FROM [dbo].[Junk_Borrowing];
DELETE FROM [dbo].[Junk_Donation];
DELETE FROM [dbo].[Patron];
DELETE FROM [dbo].[Patron_date_joined];

DBCC CHECKIDENT ('[dbo].[Artist]', RESEED, 0);
DBCC CHECKIDENT ('[dbo].[Artwork]', RESEED, 0);
DBCC CHECKIDENT ('[dbo].[Borrowed_or_lent]', RESEED, 0);
DBCC CHECKIDENT ('[dbo].[Institution]', RESEED, 0);
DBCC CHECKIDENT ('[dbo].[Junk_Borrowing]', RESEED, 0);
DBCC CHECKIDENT ('[dbo].[Junk_Donation]', RESEED, 0);
DBCC CHECKIDENT ('[dbo].[Patron]', RESEED, 0);

ALTER TABLE [dbo].[A_B_L] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[A_D] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[Artist] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[Artwork] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[Borrowed_or_lent] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[Donation] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[Institution] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[Junk_Borrowing] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[Junk_Donation] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[Patron] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [dbo].[Patron_date_joined] WITH CHECK CHECK CONSTRAINT ALL;

